# Generated by Django 5.0.4 on 2024-04-26 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=6)),
                ('marca', models.CharField(max_length=20)),
                ('model', models.IntegerField()),
            ],
        ),
    ]
