# Generated by Django 5.0.4 on 2024-04-26 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiculo',
            old_name='model',
            new_name='modelo',
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='color_vehiculo',
            field=models.CharField(choices=[('1', 'ROJO'), ('3', 'VERDE'), ('2', 'AZUL')], default=1, max_length=1, verbose_name='color'),
            preserve_default=False,
        ),
    ]
